### ISSUE TITLE
fails to build for jupyterlab 1.2.6 on ubuntu 18.04: ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/settingregistry'

### ISSUE THREAD

**Issue by rbavery** [krassowski/jupyterlab-go-to-definition#20]
```
# rave at rave-desktop in ~/iclr_challenge on git:master ✖︎ [13:59:54]
→ cat /tmp/jupyterlab-debug-qwsd1rcc.log

Yarn configuration loaded.
Node v13.8.0

> /home/rave/miniconda3/envs/data-science-stack-2.2.0/bin/npm pack @krassowski/jupyterlab_go_to_definition
npm notice 
npm notice 📦  @krassowski/jupyterlab_go_to_definition@1.0.0
npm notice === Tarball Contents === 
npm notice 2.5kB  package.json                                
npm notice 1.5kB  LICENSE                                     
npm notice 6.4kB  README.md                                   
npm notice 731B   lib/editors/codemirror/extension.d.ts       
npm notice 6.3kB  lib/editors/codemirror/extension.js         
npm notice 4.4kB  lib/editors/codemirror/extension.js.map     
npm notice 11B    lib/editors/codemirror/extension.spec.d.ts  
npm notice 2.2kB  lib/editors/codemirror/extension.spec.js    
npm notice 2.4kB  lib/editors/codemirror/extension.spec.js.map
npm notice 104B   lib/editors/codemirror/index.d.ts           
npm notice 137B   lib/editors/codemirror/index.js             
npm notice 211B   lib/editors/codemirror/index.js.map         
npm notice 409B   lib/editors/codemirror/tokens.d.ts          
npm notice 349B   lib/editors/codemirror/tokens.js            
npm notice 440B   lib/editors/codemirror/tokens.js.map        
npm notice 478B   lib/editors/editor.d.ts                     
npm notice 34B    lib/editors/editor.js                       
npm notice 115B   lib/editors/editor.js.map                   
npm notice 427B   lib/history.d.ts                            
npm notice 980B   lib/history.js                              
npm notice 970B   lib/history.js.map                          
npm notice 228B   lib/index.d.ts                              
npm notice 7.5kB  lib/index.js                                
npm notice 5.6kB  lib/index.js.map                            
npm notice 891B   lib/jump.d.ts                               
npm notice 32B    lib/jump.js                                 
npm notice 100B   lib/jump.js.map                             
npm notice 912B   lib/jumpers/fileeditor.d.ts                 
npm notice 2.9kB  lib/jumpers/fileeditor.js                   
npm notice 2.8kB  lib/jumpers/fileeditor.js.map               
npm notice 2.2kB  lib/jumpers/jumper.d.ts                     
npm notice 11.9kB lib/jumpers/jumper.js                       
npm notice 8.5kB  lib/jumpers/jumper.js.map                   
npm notice 1.0kB  lib/jumpers/notebook.d.ts                   
npm notice 5.5kB  lib/jumpers/notebook.js                     
npm notice 4.1kB  lib/jumpers/notebook.js.map                 
npm notice 3.0kB  lib/languages/analyzer.d.ts                 
npm notice 7.5kB  lib/languages/analyzer.js                   
npm notice 6.2kB  lib/languages/analyzer.js.map               
npm notice 11B    lib/languages/analyzer.spec.d.ts            
npm notice 1.6kB  lib/languages/analyzer.spec.js              
npm notice 1.6kB  lib/languages/analyzer.spec.js.map          
npm notice 301B   lib/languages/chooser.d.ts                  
npm notice 568B   lib/languages/chooser.js                    
npm notice 485B   lib/languages/chooser.js.map                
npm notice 1.2kB  lib/languages/python.d.ts                   
npm notice 10.8kB lib/languages/python.js                     
npm notice 6.5kB  lib/languages/python.js.map                 
npm notice 11B    lib/languages/python.spec.d.ts              
npm notice 13.4kB lib/languages/python.spec.js                
npm notice 12.7kB lib/languages/python.spec.js.map            
npm notice 584B   lib/languages/r.d.ts                        
npm notice 2.8kB  lib/languages/r.js                          
npm notice 2.4kB  lib/languages/r.js.map                      
npm notice 11B    lib/languages/r.spec.d.ts                   
npm notice 3.9kB  lib/languages/r.spec.js                     
npm notice 3.9kB  lib/languages/r.spec.js.map                 
npm notice 551B   lib/notebook_private.d.ts                   
npm notice 2.0kB  lib/notebook_private.js                     
npm notice 1.6kB  lib/notebook_private.js.map                 
npm notice 761B   lib/testutils.d.ts                          
npm notice 1.1kB  lib/testutils.js                            
npm notice 1.2kB  lib/testutils.js.map                        
npm notice 291B   schema/plugin.json                          
npm notice 2.1kB  src/editors/codemirror/extension.spec.ts    
npm notice 6.2kB  src/editors/codemirror/extension.ts         
npm notice 104B   src/editors/codemirror/index.ts             
npm notice 476B   src/editors/codemirror/tokens.ts            
npm notice 466B   src/editors/editor.ts                       
npm notice 1.2kB  src/history.ts                              
npm notice 7.0kB  src/index.ts                                
npm notice 838B   src/jump.ts                                 
npm notice 3.1kB  src/jumpers/fileeditor.ts                   
npm notice 12.8kB src/jumpers/jumper.ts                       
npm notice 5.6kB  src/jumpers/notebook.ts                     
npm notice 1.7kB  src/languages/analyzer.spec.ts              
npm notice 8.0kB  src/languages/analyzer.ts                   
npm notice 740B   src/languages/chooser.ts                    
npm notice 12.7kB src/languages/python.spec.ts                
npm notice 10.5kB src/languages/python.ts                     
npm notice 3.6kB  src/languages/r.spec.ts                     
npm notice 2.6kB  src/languages/r.ts                          
npm notice 2.0kB  src/notebook_private.ts                     
npm notice 1.4kB  src/testutils.ts                            
npm notice 166B   src/typings.d.ts                            
npm notice 0      style/index.css                             
npm notice === Tarball Details === 
npm notice name:          @krassowski/jupyterlab_go_to_definition         
npm notice version:       1.0.0                                           
npm notice filename:      krassowski-jupyterlab_go_to_definition-1.0.0.tgz
npm notice package size:  61.7 kB                                         
npm notice unpacked size: 255.7 kB                                        
npm notice shasum:        c935050509f0e2c7fb5311804f2e9449f037d869        
npm notice integrity:     sha512-znCdf94NCBTos[...]3b9QYUnMxzQwg==        
npm notice total files:   86                                              
npm notice 
krassowski-jupyterlab_go_to_definition-1.0.0.tgz

Yarn configuration loaded.
Node v13.8.0

Building jupyterlab assets (build:prod:minimize)
> node /home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "ipyvolume > three-text2d@0.4.1" has unmet peer dependency "@types/three@*".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/application@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/apputils@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/codeeditor@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/codemirror@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/coreutils@~4.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/docmanager@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/docregistry@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/fileeditor@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/notebook@~2.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/observables@~3.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/services@~5.0.0".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has unmet peer dependency "@lumino/algorithm@*".
warning " > @krassowski/jupyterlab_go_to_definition@1.0.0" has unmet peer dependency "codemirror@*".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 2.08s.

> node /home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 0.23s.

> node /home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/settingregistry' in '/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab_go_to_definition/lib'
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
resolve '@jupyterlab/settingregistry' in '/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab_go_to_definition/lib'
  Parsed request is a module
  using description file: /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab_go_to_definition/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab_go_to_definition/lib/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab_go_to_definition/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@krassowski/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/data-science-stack-2.2.0/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/envs/node_modules doesn't exist or is not a directory
      /home/rave/miniconda3/node_modules doesn't exist or is not a directory
      /home/rave/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules
        using description file: /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/package.json (relative path: ./node_modules/@jupyterlab/settingregistry)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.json doesn't exist
            as directory
              /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry doesn't exist
child_process.js:632
    throw err;
    ^

Error: Command failed: /home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/home/rave/miniconda3/envs/data-science-stack-2.2.0/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12245,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/home/rave/miniconda3/envs/data-science-stack-2.2.0/lib/python3.7/site-packages/jupyterlab/commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

```

Here is my jupyter version info

```
# rave at rave-desktop in ~/iclr_challenge on git:master ✖︎ [14:10:10]
→ jupyter --version                                                  
jupyter core     : 4.6.2
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```

**Comment by krassowski** [comment]
Please use:
```
jupyter labextension install @krassowski/jupyterlab_go_to_definition@0.7.1
```
for JupyterLab 1.x
